Repository lachenlama/ez_Unix, pull requests merged in 2021-10, with the labels that each got.

#1 the ls command
  ls/ls.txt
  ls/ls_screenshot.png
Labels: hacktoberfest, hacktoberfest-accepted

#2 added df and history command
  README.md
  df/README.md
  history/README.md
Labels: hacktoberfest-accepted

#5 add cd
  README.md
  cd/cd.txt
  cd/cd_screenshot.png
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#19 Lachenlama
  ls/ls.md
  ls/ls.txt
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#6 Added the mkdir command
  README.md
  mkdir/README.md
  mkdir/mkdir_screenshot.png
Labels: hacktoberfest, hacktoberfest-accepted

#22 Update and rename chmod.txt to chmod.md
  chmod/chmod.md
  chmod/chmod.txt
Labels: hacktoberfest-accepted

#20 added echo command
  echo/echo.md
Labels: hacktoberfest-accepted

#28 Add grep command
  grep/grep.md
Labels: hacktoberfest, hacktoberfest-accepted

#29 📝 Add head command
  head/head.md
Labels: hacktoberfest-accepted

#21 Added man command.
  man/man.md
Labels: hacktoberfest, hacktoberfest-accepted
